"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'apps.common',
    'apps.iam',
    'rest_framework_simplejwt.token_blacklist',
    'apps.notification',
    'apps.cloud',
    'apps.files',
    'apps.transfers',
    'apps.activity.apps.ActivityConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.common.middleware.request_id.RequestIdMiddleware',
]

ROOT_URLCONF = 'core.urls'


WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv("DB_ENGINE"),
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
    }
}

AUTH_USER_MODEL = "iam.User"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": 'apps.common.validators.password.PasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Email configuration

EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")

EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT"))

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS") == "True"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL") == "True"

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")
SERVER_EMAIL = os.getenv("SERVER_EMAIL")

PLATFORM_LOGO_URL = os.getenv("PLATFORM_LOGO_URL", "")


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [
            BASE_DIR / "templates"
        ],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

EMAIL_VERIFICATION_EXPIRY_HOURS = int(os.getenv("EMAIL_VERIFICATION_EXPIRY_HOURS", 24))

FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173").rstrip("/")

SECURE_TOKEN_BYTES = int(os.getenv("SECURE_TOKEN_BYTES", 32))

PASSWORD_RESET_TOKEN_EXPIRY_MINUTES = int(os.getenv("PASSWORD_RESET_TOKEN_EXPIRY_MINUTES", 15))

CREDENTIALS_ENCRYPTION_KEY = os.getenv("CREDENTIALS_ENCRYPTION_KEY", "")

GOOGLE_OAUTH_CLIENT_ID = os.getenv("GOOGLE_OAUTH_CLIENT_ID", "")
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv("GOOGLE_OAUTH_CLIENT_SECRET", "")
GOOGLE_OAUTH_REDIRECT_URI = os.getenv("GOOGLE_OAUTH_REDIRECT_URI", "").rstrip("/")

GOOGLE_OAUTH_SCOPES = [
    "https://www.googleapis.com/auth/drive",
    "https://www.googleapis.com/auth/userinfo.email",
    "openid",
]

DROPBOX_OAUTH_APP_KEY = os.getenv("DROPBOX_OAUTH_APP_KEY", "")
DROPBOX_OAUTH_APP_SECRET = os.getenv("DROPBOX_OAUTH_APP_SECRET", "")
DROPBOX_OAUTH_REDIRECT_URI = os.getenv("DROPBOX_OAUTH_REDIRECT_URI", "").rstrip("/")

DROPBOX_OAUTH_SCOPES = [
    "account_info.read",
    "files.metadata.read",
    "files.metadata.write",
    "files.content.read",
    "files.content.write",
    "sharing.read",
    "sharing.write",
]

ONEDRIVE_OAUTH_CLIENT_ID = os.getenv("ONEDRIVE_OAUTH_CLIENT_ID", "")
ONEDRIVE_OAUTH_CLIENT_SECRET = os.getenv("ONEDRIVE_OAUTH_CLIENT_SECRET", "")
ONEDRIVE_OAUTH_REDIRECT_URI = os.getenv("ONEDRIVE_OAUTH_REDIRECT_URI", "").rstrip("/")
ONEDRIVE_OAUTH_TENANT = os.getenv("ONEDRIVE_OAUTH_TENANT", "common")

ONEDRIVE_OAUTH_SCOPES = [
    "offline_access",
    "User.Read",
    "Files.ReadWrite",
]

OAUTH_STATE_EXPIRY_MINUTES = int(os.getenv("OAUTH_STATE_EXPIRY_MINUTES", 10))

CLOUD_OAUTH_SUCCESS_URL = (
    f"{FRONTEND_URL}{os.getenv('CLOUD_OAUTH_SUCCESS_PATH', '/cloud/connections/success')}"
)
CLOUD_OAUTH_ERROR_URL = (
    f"{FRONTEND_URL}{os.getenv('CLOUD_OAUTH_ERROR_PATH', '/cloud/connections/error')}"
)

PASSWORD_RESET_FRONTEND_URL = f"{FRONTEND_URL}/reset-password"

EMAIL_VERIFICATION_FRONTEND_URL = f"{FRONTEND_URL}/verify-email"

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CORS_ALLOWED_ORIGINS", FRONTEND_URL).split(",")
    if origin.strip()
]

CORS_ALLOW_CREDENTIALS = True

CORS_EXPOSE_HEADERS = [
    "Content-Disposition",
]

MAX_FILE_UPLOAD_SIZE_BYTES = int(
    os.getenv("MAX_FILE_UPLOAD_SIZE_BYTES", 104857600)
)
FILE_LIST_DEFAULT_PAGE_SIZE = int(
    os.getenv("FILE_LIST_DEFAULT_PAGE_SIZE", 50)
)
FILE_LIST_MAX_PAGE_SIZE = int(os.getenv("FILE_LIST_MAX_PAGE_SIZE", 100))

# Celery (Phase 4) — broker/result via Redis; single default queue.
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv(
    "CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/1"
)
CELERY_TASK_ALWAYS_EAGER = os.getenv("CELERY_TASK_ALWAYS_EAGER", "False") == "True"
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_TASK_TRACK_STARTED = True
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_DEFAULT_QUEUE = "default"
# Extensible later, e.g. {"apps.transfers.tasks.*": {"queue": "transfers"}}
CELERY_TASK_ROUTES: dict = {}
CELERY_WORKER_HEALTH_TIMEOUT_SECONDS = float(
    os.getenv("CELERY_WORKER_HEALTH_TIMEOUT_SECONDS", "2")
)

MAX_TRANSFER_SIZE_BYTES = int(
    os.getenv("MAX_TRANSFER_SIZE_BYTES", str(100 * 1024 * 1024))
)