# Generated by Django 6.0.7 on 2026-08-05 18:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudConnection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('google_drive', 'Google Drive'), ('dropbox', 'Dropbox'), ('onedrive', 'OneDrive')], db_index=True, max_length=32)),
                ('display_name', models.CharField(max_length=150)),
                ('provider_account_id', models.CharField(max_length=255)),
                ('account_email', models.EmailField(blank=True, default='', max_length=254)),
                ('credentials_encrypted', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('disabled', 'Disabled'), ('expired', 'Expired'), ('error', 'Error')], db_index=True, default='pending', max_length=32)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('quota_total_bytes', models.BigIntegerField(blank=True, null=True)),
                ('quota_used_bytes', models.BigIntegerField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cloud_connections',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'provider', 'status'], name='cloud_conn_user_prov_status')],
                'constraints': [models.UniqueConstraint(fields=('user', 'provider', 'provider_account_id'), name='uniq_user_provider_account')],
            },
        ),
    ]
