# Generated by Django 6.0.7 on 2026-07-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='invalidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
