# Generated by Django 6.0.7 on 2026-07-31 13:14

import apps.common.utils.token
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_emailverificationtoken_invalidated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(default=apps.common.utils.token.generate_secure_token, editable=False, max_length=64, unique=True),
        ),
    ]
