# Generated by Django 6.0.7 on 2026-07-31 13:18

import apps.common.utils.token
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0004_alter_emailverificationtoken_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.common.utils.token.generate_secure_token, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reset_password_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='reset_passw_token_172983_idx'), models.Index(fields=['user', 'is_used'], name='reset_passw_user_id_c3afcb_idx'), models.Index(fields=['expires_at'], name='reset_passw_expires_e6b655_idx')],
            },
        ),
    ]
