# Generated by Django 6.0.7 on 2026-08-13 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cloud', '0002_oauth_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('connection.linked', 'Connection linked'), ('connection.unlinked', 'Connection unlinked'), ('connection.disabled', 'Connection disabled'), ('connection.enabled', 'Connection enabled'), ('file.uploaded', 'File uploaded'), ('file.folder_created', 'Folder created'), ('file.renamed', 'File renamed'), ('file.moved', 'File moved'), ('file.trashed', 'File trashed'), ('file.deleted', 'File deleted'), ('file.copied', 'File copied'), ('file.restored', 'File restored'), ('transfer.created', 'Transfer created'), ('transfer.cancel_requested', 'Transfer cancel requested'), ('transfer.cancelled', 'Transfer cancelled'), ('transfer.completed', 'Transfer completed'), ('transfer.failed', 'Transfer failed')], db_index=True, max_length=64)),
                ('resource_type', models.CharField(choices=[('connection', 'Connection'), ('file', 'File'), ('folder', 'Folder'), ('transfer', 'Transfer')], db_index=True, max_length=32)),
                ('resource_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('resource_name', models.CharField(blank=True, default='', max_length=512)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='cloud.cloudconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='activity_user_created'), models.Index(fields=['user', 'action'], name='activity_user_action'), models.Index(fields=['user', 'resource_type'], name='activity_user_resource'), models.Index(fields=['user', 'connection'], name='activity_user_connection')],
            },
        ),
    ]
