# Generated by Django 6.0.7 on 2026-08-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('connection.linked', 'Connection linked'), ('connection.unlinked', 'Connection unlinked'), ('connection.disabled', 'Connection disabled'), ('connection.enabled', 'Connection enabled'), ('file.uploaded', 'File uploaded'), ('file.folder_created', 'Folder created'), ('file.renamed', 'File renamed'), ('file.moved', 'File moved'), ('file.trashed', 'File trashed'), ('file.deleted', 'File deleted'), ('file.copied', 'File copied'), ('file.restored', 'File restored'), ('transfer.created', 'Transfer created'), ('transfer.cancel_requested', 'Transfer cancel requested'), ('transfer.cancelled', 'Transfer cancelled'), ('transfer.completed', 'Transfer completed'), ('transfer.failed', 'Transfer failed'), ('auth.password_changed', 'Password changed'), ('auth.password_reset_requested', 'Password reset requested'), ('auth.password_reset_completed', 'Password reset completed'), ('auth.email_verified', 'Email verified'), ('auth.logout_all_devices', 'Logged out all devices')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='resource_type',
            field=models.CharField(choices=[('connection', 'Connection'), ('file', 'File'), ('folder', 'Folder'), ('transfer', 'Transfer'), ('account', 'Account')], db_index=True, max_length=32),
        ),
    ]
