# Generated by Django 6.0.7 on 2026-08-11 17:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cloud', '0002_oauth_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(choices=[('copy', 'Copy'), ('move', 'Move'), ('copy_all', 'Copy all'), ('move_all', 'Move all')], max_length=32)),
                ('conflict_policy', models.CharField(choices=[('reject', 'Reject'), ('rename', 'Rename')], default='reject', max_length=16)),
                ('source_item_id', models.CharField(max_length=255)),
                ('source_item_name', models.CharField(blank=True, default='', max_length=512)),
                ('source_is_folder', models.BooleanField(default=False)),
                ('dest_parent_id', models.CharField(default='root', max_length=255)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('items_total', models.PositiveIntegerField(default=0)),
                ('items_completed', models.PositiveIntegerField(default=0)),
                ('items_failed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('planning', 'Planning'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partial_success', 'Partial success')], db_index=True, default='pending', max_length=32)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dest_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_transfer_jobs', to='cloud.cloudconnection')),
                ('source_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_transfer_jobs', to='cloud.cloudconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transfer_jobs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('file', 'File'), ('folder', 'Folder')], max_length=16)),
                ('source_item_id', models.CharField(max_length=255)),
                ('source_path', models.CharField(blank=True, default='', max_length=1024)),
                ('source_name', models.CharField(max_length=512)),
                ('dest_parent_id', models.CharField(blank=True, default='', max_length=255)),
                ('dest_item_id', models.CharField(blank=True, default='', max_length=255)),
                ('dest_name', models.CharField(blank=True, default='', max_length=512)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=32)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transfers.transferjob')),
            ],
            options={
                'db_table': 'transfer_items',
                'ordering': ('sequence', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='transferjob',
            index=models.Index(fields=['user', 'status', 'created_at'], name='xfer_job_user_status_created'),
        ),
        migrations.AddIndex(
            model_name='transferitem',
            index=models.Index(fields=['job', 'status'], name='xfer_item_job_status'),
        ),
    ]
